### ISSUE TITLE
LdesClientRunner FAILURE, org.apache.jena.riot.RiotException: [line: 1, col: 1 ] The document could not be loaded or parsed [code=LOADING_DOCUMENT_FAILED].

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#164]
**Prerequisites:**

The version is : `LDI_ORCHESTRATOR_TAG=20230407T130529`
I am trying to configure LDES-Client to replicate the LDES stream from the endpoint:` https://apim-iow-apimanagement.azure-api.net/ldes/water-quality-observations-by-time`

The configuration in the ldio-workflow is: 

```
server:
  port: 8082
orchestrator:
  pipelines:
    - name: simulator-to-server-pipeline
      description: "This pipeline uses an LDES client to read an existing LDES and send the members as N-Quads to a LDES Server"
      input:
        name: be.vlaanderen.informatievlaanderen.ldes.ldi.client.LdioLdesClient
        config:
          url: https://apim-iow-apimanagement.azure-api.net/ldes/water-quality-observations/water-quality-observations-by-time
        # TODO: remove this TEMP workaround (adapter | name)
        adapter:
          name: be.vlaanderen.informatievlaanderen.ldes.ldi.RdfAdapter
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpOut
          config:
            endpoint: http://ldes-server-observations:8080/water-quality-observations
            content-type: application/n-quads

```
please see: ldio-workflow.config.yml in
[water-quality-observations.zip](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/files/11330653/water-quality-observations.zip)

**Scenario:**
run:` docker compose --user-file .env  up ldio-workflow -d` to start the ldio-workflow

**Current result:**
```
2023-04-26 10:25:16 2023-04-26T08:25:16.346Z  INFO 1 --- [pool-4-thread-1] b.v.i.ldes.ldio.LdesClientRunner         : LdesClientRunner setup finished
2023-04-26 10:25:16 JsonLdError[code=The document could not be loaded or parsed [code=LOADING_DOCUMENT_FAILED]., message=The document could not be loaded or parsed [code=LOADING_DOCUMENT_FAILED].]
```
[failure.txt](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/files/11330679/failure.txt)

**Expected result:**
The LdesClient should be able to parse/replicate an LDES stream in JSON-LD format.
