### ISSUE TITLE
LDES client nifi component can't handle redirections 

### ISSUE THREAD

**Issue by cedricdcc** [Informatievlaanderen/VSDS-Linked-Data-Interactions#179]
**Describe the bug**

When trying to use the[ LDES client nifi processor component](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/blob/main/ldi-nifi/ldi-nifi-processors/ldes-client-processor/src/main/java/be/vlaanderen/informatievlaanderen/ldes/ldi/processors/LdesClient.java) I get back the following error:

![stacktrace nifi-graph2 container](https://user-images.githubusercontent.com/30471340/236209905-a4168576-0dad-4436-b525-6b1311f1003e.JPG)

**To Reproduce**

1. docker-compose up --build with the following yml file: 
 ```yml
version: ‘3'
volumes:
  nifi-database-repository:
  nifi-flowfile-repository:
  nifi-content-repository:
  nifi-provenance-repository:
  nifi-state:
  nifi-logs:
  nifi-nars:
  nifi-conf:
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
services:
  nifi:
    image: ghcr.io/informatievlaanderen/ldi-workbench-nifi:20230417t154912 #20221109T103745
    container_name: nifi-graph2
    restart: unless-stopped
    ports:
      # HTTPS
      - 8443:8443/tcp
    volumes:
      - ./nifi-extensions:/opt/nifi/nifi-current/extensions
    environment:
      - NIFI_UI_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=admin123456789
      - NIFI_WORKFLOW_LISTEN_PORT=9005
      - NIFI_JVM_HEAP_INIT=8g
      - NIFI_JVM_HEAP_MAX=8g
  graphdb:
    image: ontotext/graphdb:10.0.2
    container_name: graphdb4
    ports:
      # HTTP
      - 7200:7200
 ```
2. open [https://localhost:8443/nifi/](https://localhost:8443/nifi/)
3. type in credentials as stated in the yml file above
4. drag in processor and select LdesClient 0.0.1-SNAPSHOT
5. fill in config of the LDES client nifi processor component:
        - Data source url : [http://marineregions.org/feed?page=2023-04-29T15%3A00%3A00Z%2F2023-04-29T16%3A00%3A00Z](http://marineregions.org/feed?page=2023-04-29T15%3A00%3A00Z%2F2023-04-29T16%3A00%3A00Z)
        - Data source format: application/ld+json
        - Data destination format: application/n-quads
        - Stream TimestampPath property to FlowFile: false
        - Stream VersionOf peroperty to FlowFile: false
        - Stream shape property to FlowFile: false
  
and all the other config settings are default.

6. Right click on component and start

**Expected behavior**

I expected the client to get all the triples from the ldes feed but instead found out that the LDES client can't handle redirects.
I was wondering why this is the case?

**Screenshots**

stacktrace crawling 1:
![bugchase1](https://user-images.githubusercontent.com/30471340/236212401-43d52b52-aa8c-4378-86dd-619146f0ec4e.JPG)

stacktrace crawling 2:
![bugchase2](https://user-images.githubusercontent.com/30471340/236212466-bf72fb70-ddba-4aa4-afc4-b944923ce0f7.JPG)

stacktrace crawling 3:
![bugchase3](https://user-images.githubusercontent.com/30471340/236212520-fe2ebb29-b45c-49fc-9713-cbe8ceebc7ec.JPG)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: firefox
 - Version 112.0.0 (64-bits)

**Additional context**
I just wanted to try and use the ldes client to harvest marine regions. I don't understand why the client stops redirects since that is the main way the LDES feed of marine regions delivers its content to the end-user.

**Comment by Tomvbe** [comment]
Redirects are supported but this was implemented with custom code. I think this was done to maintain a 1-on-1 relation between request and fragment (@WLefever-Cegeka may be able to elaborate this further).
The reason this does not work at the moment is because the code currently only supports HTTP status 302:

`	public TreeNodeResponse fetchTreeNode(TreeNodeRequest treeNodeRequest) {
		final Response response = requestExecutor.execute(treeNodeRequest.createRequest());

		return switch (response.getHttpStatus()) {
			case HttpStatus.SC_OK -> createOkResponse(treeNodeRequest, response);
			case HttpStatus.SC_MOVED_TEMPORARILY -> createMovedTemporarilyResponse(response);
			case HttpStatus.SC_NOT_MODIFIED -> createNotModifiedResponse(response);
			default -> throw new UnsupportedOperationException(
					"Cannot handle response " + response.getHttpStatus() + " of TreeNodeRequest " + treeNodeRequest);
		};
	}`

`	public StartingTreeNode determineStartingTreeNode(final StartingNodeRequest startingNodeRequest) {
		log.atInfo().log("determineStartingTreeNode for: " + startingNodeRequest.url());
		RequestHeaders requestHeaders = new RequestHeaders(
				List.of(new RequestHeader(HttpHeaders.ACCEPT, startingNodeRequest.contentType())));
		Response response = requestExecutor.execute(new Request(startingNodeRequest.url(), requestHeaders));
		if (response.hasStatus(HttpStatus.SC_OK)) {
			return selectStartingNode(startingNodeRequest, response);
		}
		if (response.hasStatus(HttpStatus.SC_MOVED_TEMPORARILY)) {
			StartingNodeRequest newStartingNodeRequest = startingNodeRequest
					.createRedirectedEndpoint(response.getFirstHeaderValue(HttpHeaders.LOCATION)
							.orElseThrow(() -> new StartingNodeNotFoundException(startingNodeRequest.url(),
									"No Location Header in redirect.")));
			return determineStartingTreeNode(newStartingNodeRequest);
		}
		throw new StartingNodeNotFoundException(startingNodeRequest.url(),
				"Unable to hande response " + response.getHttpStatus());
	}`

The checks for HttpStatus.SC_MOVED_TEMPORARILY should check for all different 3xx redirect codes.

**Comment by marc-portier** [comment]
Surely useful, but not sure it is going to help us more then just one extra level of redirection.

We do indeed have a 301 redirect for the http-vs-http**s** setup - which is documented in the original question
but if we avoid that we still have a weird effect based on a sequence of 302 redirects that don't seem to be handled as expected either.

The remainder of the redirects goes like this:
* `GET http://marineregions.org/feed ==> yields 301 to https://marineregions.org/feed` + html-body no content
* `GET https://marineregions.org/feed ==> yields 302 to https://marineregions.org/feed.ttl` + html-body no content
* `GET https://marineregions.org/feed.ttl ==> yields 302 to https://marineregions.org/feed.ttl?page={time-window-indicator}` + html-body with 
* `GET https://marineregions.org/feed.ttl?page={time-window-indicator} ==> yields 200 with turtle content describing the feed <http://marineinfo.org/feed>`

However when we enter any of those later URI (connected to the final resource through noting but 302 redirects!) as a reference to the feed we get a very weird error:

![image](https://user-images.githubusercontent.com/299574/236251240-fd751346-935c-4bc8-99ce-301218d204ad.png)

Our (maybe wild?) guess is that some part in the process is assuming that `<!DOCTYPE html>` is the start of a turtle or n3 file?
Because of that it tries to tokenize the first <subject-uri> in that file and comes to the conclusion that "!DOCTYPE html" is not a valid IRI because it contains a space?

This too, looked (to us) as a possible side-effect of the redirect chain?

**Comment by Tomvbe** [comment]
There were two issues with the client:

1. Only 302 was supported.
2. Only absolute paths in the location header were supported.

I created a PR (https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/pull/181) to fix both of these:

1. 301, 302, 307 and 308 redirects will be supported.
2. Absolute paths and relative paths (starting with / and without /) will be supported.

With these fixes I am able to following the marine regions:

![image](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/assets/34196062/ae07d926-37e4-4f48-bf0d-9c0def5fd275)

**Comment by cedricdcc** [comment]
@Tomvbe what steps / processes did you use to get to the output screenshot you posted above? Do you have the docker-compose file or the specific docker image that you used?

**Comment by Tomvbe** [comment]
The above was done with the LDI orchestrator and the following configuration:

```
orchestrator:
  pipelines:
    - name: wkt
      input:
        adapter:
          name: be.vlaanderen.informatievlaanderen.ldes.ldi.RdfAdapter
        name: be.vlaanderen.informatievlaanderen.ldes.ldi.client.LdioLdesClient
        config:
          url: http://marineregions.org/feed
          source-format: text/turtle
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioConsoleOut
          config:
            content-type: application/n-quads
```

I just retested it with the latest image and it still works with LDIO.
