### ISSUE TITLE
Docker image: 20230130T1553, LDES Client cli crashed with the phantom relation.

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#28]
**Prerequisites:**
Test set up: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/gtfs-and-rt/6.basic-retention

Add
```
 ldes-cli:
    image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldes-cli:${LDES_CLIENT_CLI_TAG:-20230206t0943}
    container_name: ${USECASE_NAME:-setup-caching}_ldes-client-cli
    command: "--url http://localhost:${NGINX_PORT:-8080}/${COLLECTION_NAME:-mobility-hindrances}/${VIEW_NAME:-by-short-time} --input-format text/turtle"
    profiles:
      - delayed-started
    # use the network stack of the nginx service so that 
    # localhost refers to nginx and we can follow the LDES stream both from the host as from within the CLI
    network_mode: service:ldes-server

```
to the  [docker-compose.yml](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/gtfs-and-rt/6.basic-retention/docker-compose.yml),  to start the ldes-cli for printing the LDES Stream to the console. (please modify it accordingly)

LDES_CLIENT_CLI_TAG=20230130T1553 (For avoiding the overlapping issue: https://github.com/Informatievlaanderen/VSDS-LDESWorkbench-Services/issues/102)

**Scenario:**
1. Follow E2E test [6.basic-retention]( https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/gtfs-and-rt/6.basic-retention) till some fragments are soft/hard deleted in the` by-short-time` view
2.  run `docker compose --env-file user.env up ldes-cli` to start the ldes-cli (modify accordingly)

**Current:**
`ldes-cli' starts printing the LDES stream followed by the ` by-short-time` view on the docker console
At one moment, `ldes-cli' docker container  crashed/stopped without any logs

**Expected:**
The  `ldes-cli:` docker container should not crashed.

Please feel free to correct me I am wrong, or you cannot replicate the issue.
Thanks 
XD
