### ISSUE TITLE
LDES Client unable to fetch fragments from Geomobility LDES

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/VSDS-Linked-Data-Interactions#458]
**Describe the bug**
The LDES Client generates the following error when trying to replicate the Geomobility LDES (Brugge):
`Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`. It indicates that the certificate is not valid. However, when checking the certificate using the browser, it show that it is valid.

**To Reproduce**
Used the following `docker-compose.yml`:
```yml
version: "3.5"
services:
  ldio:
    image: ghcr.io/informatievlaanderen/ldi-orchestrator:latest
    container_name: ldio
    ports:
      - 8082:8080
    volumes:
      - ./config/ldio-config.yml:/ldio/application.yml:ro
```

With the following LDIO config:
```yml
server:
  port: 8082
orchestrator:
  pipelines:
    - name: ldes
      input:
        name: be.vlaanderen.informatievlaanderen.ldes.ldi.client.LdioLdesClient
        config:
          url: https://brugge-ldes.geomobility.eu/observations/by-page?pageNumber=1
          sourceFormat: text/turtle
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioConsoleOut
          config:
            rdf-writer:
             content-type: application/n-quads
```

**Expected behavior**
I expect the Geomobility LDES members to be outputted as N-Quads.

**Comment by sandervd** [comment]
It seems the certificate authority is not universally accepted, and not included in the CA store of the OS (perhaps it is in some browsers?).
On a linux box it's easy to confirm the issue:
![image](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/assets/1673560/abe8ca9d-350a-4c63-8b53-41b1a1aee6bd)
I would recommend using a ssl certificated from a broad accepted provider (let's encrypt would work just fine).
I setup a temporary proxy so at least you can fetch the data: https://geomobility.essentialcomplexity.eu

**Comment by Tomvbe** [comment]
As @sandervd indicated, the issue is caused by the use of an untrusted certificate by the server hosting https://brugge-ldes.geomobility.eu/observations.

A workaround for this is the following `docker-compose.yml`:

```
version: "3.5"
services:
  ldio:
    image: ghcr.io/informatievlaanderen/ldi-orchestrator:latest
    container_name: ldio
    ports:
      - 8082:8080
    volumes:
      - ./config/ldio-config.yml:/ldio/application.yml:ro
      - ./my-cert.crt:/tmp/my-cert.crt
    entrypoint: >
      /bin/sh -c '
      keytool -import -alias mycert -keystore /usr/local/openjdk-18/lib/security/cacerts -file /tmp/my-cert.crt -storepass changeit -noprompt &&
      exec java -cp ldio-application.jar -Dloader.path=lib/ org.springframework.boot.loader.launch.PropertiesLauncher'
    user: root
``` 

And creating a new file in the same directory as your docker-compose.yml called `my-cert.crt`  with the following content:

```
-----BEGIN CERTIFICATE-----
MIIGEzCCA/ugAwIBAgIQfVtRJrR2uhHbdBYLvFMNpzANBgkqhkiG9w0BAQwFADCB
iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl
cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV
BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTgx
MTAyMDAwMDAwWhcNMzAxMjMxMjM1OTU5WjCBjzELMAkGA1UEBhMCR0IxGzAZBgNV
BAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UE
ChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4g
VmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEA1nMz1tc8INAA0hdFuNY+B6I/x0HuMjDJsGz99J/LEpgPLT+N
TQEMgg8Xf2Iu6bhIefsWg06t1zIlk7cHv7lQP6lMw0Aq6Tn/2YHKHxYyQdqAJrkj
eocgHuP/IJo8lURvh3UGkEC0MpMWCRAIIz7S3YcPb11RFGoKacVPAXJpz9OTTG0E
oKMbgn6xmrntxZ7FN3ifmgg0+1YuWMQJDgZkW7w33PGfKGioVrCSo1yfu4iYCBsk
Haswha6vsC6eep3BwEIc4gLw6uBK0u+QDrTBQBbwb4VCSmT3pDCg/r8uoydajotY
uK3DGReEY+1vVv2Dy2A0xHS+5p3b4eTlygxfFQIDAQABo4IBbjCCAWowHwYDVR0j
BBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFI2MXsRUrYrhd+mb
+ZsF4bgBjWHhMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAbBgNVHSAEFDASMAYGBFUdIAAw
CAYGZ4EMAQIBMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0
LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2Bggr
BgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNv
bS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDov
L29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQwFAAOCAgEAMr9hvQ5Iw0/H
ukdN+Jx4GQHcEx2Ab/zDcLRSmjEzmldS+zGea6TvVKqJjUAXaPgREHzSyrHxVYbH
7rM2kYb2OVG/Rr8PoLq0935JxCo2F57kaDl6r5ROVm+yezu/Coa9zcV3HAO4OLGi
H19+24rcRki2aArPsrW04jTkZ6k4Zgle0rj8nSg6F0AnwnJOKf0hPHzPE/uWLMUx
RP0T7dWbqWlod3zu4f+k+TY4CFM5ooQ0nBnzvg6s1SQ36yOoeNDT5++SR2RiOSLv
xvcRviKFxmZEJCaOEDKNyJOuB56DPi/Z+fVGjmO+wea03KbNIaiGCpXZLoUmGv38
sbZXQm2V0TP2ORQGgkE49Y9Y3IBbpNV9lXj9p5v//cWoaasm56ekBYdbqbe4oyAL
l6lFhd2zi+WJN44pDfwGF/Y4QA5C5BIG+3vzxhFoYt/jmPQT2BVPi7Fp2RBgvGQq
6jG35LWjOhSbJuMLe/0CjraZwTiXWTb2qHSihrZe68Zk6s+go/lunrotEbaGmAhY
LcmsJWTyXnW0OMGuf1pGg+pRyrbxmRE1a6Vqe8YAsOf4vmSyrcjC8azjUeqkk+B5
yOGBQMkKW+ESPMFgKuOXwIlCypTPRpgSabuY0MLTDXJLR27lk8QyKGOHQ+SwMj4K
00u/I5sUKUErmgQfky3xxzlIPK1aEn8=
-----END CERTIFICATE-----

```
