### ISSUE TITLE
Version Materialiser + repository materialiser gives no response

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/VSDS-Linked-Data-Interactions#501]
**Describe the bug**
Pipeline I use: LDES -> Version materialiser -> Repository materialiser 

The repository materialiser returns an I/O exception when the version materialiser is used in the transformers step.
This probably has to do with the RDF4J server I use as proxy for the triple store.
Without version materialisation, I can perfectly ingest all members inside the triple store (apache Jena in my case).

Things that would help:
1. Add retry and rate limiting config to repository materialiser
2. Testing with RDF4J server as proxy so other triple stores are better supported instead of graphDB

**To Reproduce**

1. Use docker-compose file here: https://github.com/sirus-be/westtoer-win-ldes2triplestore/blob/main/docker-compose.yml
3. Use below ldio config:
```
orchestrator:
  pipelines:
    - name: touristattractions
      description: "This pipeline will take the latest version products from Westtoer, and send to an LDES server"
      input:
        name: be.vlaanderen.informatievlaanderen.ldes.ldi.client.LdioLdesClient
        config:
          url: https://ca-westtoer-ldes.bluesea-b3dcdb70.westeurope.azurecontainerapps.io/touristattractions
          sourceFormat: text/turtle
          retries:
            enabled: true
      transformers:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.VersionMaterialiser
          config:
            versionOf-property: http://purl.org/dc/terms/isVersionOf
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioConsoleOut
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.RepositoryMaterialiser
          config:
            sparql-host: http://rdf4j-server:8080/rdf4j-server
            repository-id: jena
            named-graph: http://example.org/westtoer
```

**Expected behavior**

**Screenshots**

```
westtoer_ldes2triplestore_ldio-workbench  | 2024-02-19T10:25:38.700Z  WARN 1 --- [pool-5-thread-1] tpClientSessionManager$RetryHandlerStale : Closing stale connection
westtoer_ldes2triplestore_ldio-workbench  | 2024-02-19T10:25:38.701Z  INFO 1 --- [pool-5-thread-1] o.apache.http.impl.execchain.RetryExec   : I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://rdf4j-server:8080: The target server failed to respond
westtoer_ldes2triplestore_ldio-workbench  | 2024-02-19T10:25:38.701Z  WARN 1 --- [pool-5-thread-1] o.e.r.r.h.CustomHTTPRepositoryConnection : Rolling back transaction due to connection close
westtoer_ldes2triplestore_ldio-workbench  | 
westtoer_ldes2triplestore_ldio-workbench  | java.lang.Throwable: null
westtoer_ldes2triplestore_ldio-workbench  |     at org.eclipse.rdf4j.repository.http.CustomHTTPRepositoryConnection.close(CustomHTTPRepositoryConnection.java:316) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldi.Materialiser.process(Materialiser.java:73) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.LdioRepositoryMaterialiser.accept(LdioRepositoryMaterialiser.java:21) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.LdioRepositoryMaterialiser.accept(LdioRepositoryMaterialiser.java:10) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.config.LdiOutputLogger.lambda$accept$0(LdiOutputLogger.java:27) ~[!/:na]
westtoer_ldes2triplestore_ldio-workbench  |     at io.micrometer.observation.Observation.lambda$observe$0(Observation.java:493) ~[ldio-archive-file-in-jar-with-dependencies.jar:1.11.3]
westtoer_ldes2triplestore_ldio-workbench  |     at io.micrometer.observation.Observation.observeWithContext(Observation.java:603) ~[ldio-archive-file-in-jar-with-dependencies.jar:1.11.3]
westtoer_ldes2triplestore_ldio-workbench  |     at io.micrometer.observation.Observation.observe(Observation.java:492) ~[ldio-archive-file-in-jar-with-dependencies.jar:1.11.3]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.config.LdiOutputLogger.accept(LdiOutputLogger.java:25) ~[!/:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.config.LdiOutputLogger.accept(LdiOutputLogger.java:10) ~[!/:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.services.LdioSender.lambda$apply$1(LdioSender.java:57) ~[!/:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.services.LdioSender.apply(LdioSender.java:57) ~[!/:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.types.LdioTransformer.next(LdioTransformer.java:21) ~[ldio-archive-file-in-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.config.LdioVersionMaterialiser.apply(LdioVersionMaterialiser.java:17) ~[ldio-version-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.services.ComponentExecutorImpl.transformLinkedData(ComponentExecutorImpl.java:17) ~[!/:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.types.LdioInput.lambda$processModel$1(LdioInput.java:73) ~[ldio-archive-file-in-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at io.micrometer.observation.Observation.lambda$observe$0(Observation.java:493) ~[ldio-archive-file-in-jar-with-dependencies.jar:1.11.3]
westtoer_ldes2triplestore_ldio-workbench  |     at io.micrometer.observation.Observation.observeWithContext(Observation.java:603) ~[ldio-archive-file-in-jar-with-dependencies.jar:1.11.3]
westtoer_ldes2triplestore_ldio-workbench  |     at io.micrometer.observation.Observation.observe(Observation.java:492) ~[ldio-archive-file-in-jar-with-dependencies.jar:1.11.3]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.types.LdioInput.processModel(LdioInput.java:71) ~[ldio-archive-file-in-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.LdioLdesClient.run(LdioLdesClient.java:55) ~[ldio-ldes-client-connector-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  | 
westtoer_ldes2triplestore_ldio-workbench  | 
westtoer_ldes2triplestore_ldio-workbench  | 2024-02-19T10:25:38.715Z ERROR 1 --- [pool-5-thread-1] b.v.i.l.ldio.LdioRepositoryMaterialiser  : ERROR - when='output', problem='org.eclipse.rdf4j.repository.RepositoryException: org.apache.http.client.ClientProtocolException'
westtoer_ldes2triplestore_ldio-workbench  | 2024-02-19T10:25:38.716Z ERROR 1 --- [pool-5-thread-1] b.v.i.l.l.c.LdioVersionMaterialiser      : ERROR - when='transformModel', problem='org.eclipse.rdf4j.repository.RepositoryException: org.apache.http.client.ClientProtocolException'
westtoer_ldes2triplestore_ldio-workbench  | 2024-02-19T10:25:38.716Z ERROR 1 --- [pool-5-thread-1] b.v.i.ldes.ldio.LdioLdesClient           : ERROR - when='touristattractions:processModel', problem='org.eclipse.rdf4j.repository.RepositoryException: org.apache.http.client.ClientProtocolException'
westtoer_ldes2triplestore_ldio-workbench  | 2024-02-19T10:25:38.716Z ERROR 1 --- [pool-5-thread-1] b.v.i.ldes.ldio.LdioLdesClient           : LdesClientRunner FAILURE
westtoer_ldes2triplestore_ldio-workbench  | 
westtoer_ldes2triplestore_ldio-workbench  | be.vlaanderen.informatievlaanderen.ldes.ldi.exceptions.MaterialisationFailedException: org.eclipse.rdf4j.repository.RepositoryException: org.apache.http.client.ClientProtocolException
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldi.Materialiser.process(Materialiser.java:71) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.LdioRepositoryMaterialiser.accept(LdioRepositoryMaterialiser.java:21) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.LdioRepositoryMaterialiser.accept(LdioRepositoryMaterialiser.java:10) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.config.LdiOutputLogger.lambda$accept$0(LdiOutputLogger.java:27) ~[!/:na]
westtoer_ldes2triplestore_ldio-workbench  |     at io.micrometer.observation.Observation.lambda$observe$0(Observation.java:493) ~[ldio-archive-file-in-jar-with-dependencies.jar:1.11.3]
westtoer_ldes2triplestore_ldio-workbench  |     at io.micrometer.observation.Observation.observeWithContext(Observation.java:603) ~[ldio-archive-file-in-jar-with-dependencies.jar:1.11.3]
westtoer_ldes2triplestore_ldio-workbench  |     at io.micrometer.observation.Observation.observe(Observation.java:492) ~[ldio-archive-file-in-jar-with-dependencies.jar:1.11.3]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.config.LdiOutputLogger.accept(LdiOutputLogger.java:25) ~[!/:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.config.LdiOutputLogger.accept(LdiOutputLogger.java:10) ~[!/:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.services.LdioSender.lambda$apply$1(LdioSender.java:57) ~[!/:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.services.LdioSender.apply(LdioSender.java:57) ~[!/:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.types.LdioTransformer.next(LdioTransformer.java:21) ~[ldio-archive-file-in-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.config.LdioVersionMaterialiser.apply(LdioVersionMaterialiser.java:17) ~[ldio-version-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.services.ComponentExecutorImpl.transformLinkedData(ComponentExecutorImpl.java:17) ~[!/:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.types.LdioInput.lambda$processModel$1(LdioInput.java:73) ~[ldio-archive-file-in-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at io.micrometer.observation.Observation.lambda$observe$0(Observation.java:493) ~[ldio-archive-file-in-jar-with-dependencies.jar:1.11.3]
westtoer_ldes2triplestore_ldio-workbench  |     at io.micrometer.observation.Observation.observeWithContext(Observation.java:603) ~[ldio-archive-file-in-jar-with-dependencies.jar:1.11.3]
westtoer_ldes2triplestore_ldio-workbench  |     at io.micrometer.observation.Observation.observe(Observation.java:492) ~[ldio-archive-file-in-jar-with-dependencies.jar:1.11.3]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.types.LdioInput.processModel(LdioInput.java:71) ~[ldio-archive-file-in-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldio.LdioLdesClient.run(LdioLdesClient.java:55) ~[ldio-ldes-client-connector-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  |     at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
westtoer_ldes2triplestore_ldio-workbench  | Caused by: org.eclipse.rdf4j.repository.RepositoryException: org.apache.http.client.ClientProtocolException
westtoer_ldes2triplestore_ldio-workbench  |     at org.eclipse.rdf4j.repository.http.CustomHTTPRepositoryConnection.removeModel(CustomHTTPRepositoryConnection.java:550) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at org.eclipse.rdf4j.repository.http.CustomHTTPRepositoryConnection.flushTransactionState(CustomHTTPRepositoryConnection.java:594) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at org.eclipse.rdf4j.repository.http.CustomHTTPRepositoryConnection.exportStatements(CustomHTTPRepositoryConnection.java:227) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at org.eclipse.rdf4j.repository.http.CustomHTTPRepositoryConnection.getStatements(CustomHTTPRepositoryConnection.java:216) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at org.eclipse.rdf4j.repository.RepositoryConnection.getStatements(RepositoryConnection.java:399) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldi.Materialiser.deleteEntitiesFromRepo(Materialiser.java:118) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at be.vlaanderen.informatievlaanderen.ldes.ldi.Materialiser.process(Materialiser.java:60) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     ... 36 common frames omitted
westtoer_ldes2triplestore_ldio-workbench  | Caused by: org.apache.http.client.ClientProtocolException: null
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1065) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeNoContent(SPARQLProtocolSession.java:1049) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.upload(RDF4JProtocolSession.java:1101) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.upload(RDF4JProtocolSession.java:926) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.removeData(RDF4JProtocolSession.java:911) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     at org.eclipse.rdf4j.repository.http.CustomHTTPRepositoryConnection.removeModel(CustomHTTPRepositoryConnection.java:545) ~[ldio-repository-materialiser-jar-with-dependencies.jar:na]
westtoer_ldes2triplestore_ldio-workbench  |     ... 42 common frames omitted
westtoer_ldes2triplestore_ldio-workbench  | Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:108) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     ... 50 common frames omitted
westtoer_ldes2triplestore_ldio-workbench  | Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.4.16]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.4.16]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.4.16]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.4.16]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[ldio-archive-file-in-jar-with-dependencies.jar:4.5.14]
westtoer_ldes2triplestore_ldio-workbench  |     ... 53 common frames omitted
westtoer_ldes2triplestore_ldio-workbench  | 
westtoer_ldes2triplestore_ldio-workbench  | 
```

**Additional context**
On startup, it ingests a number of members, but after a few seconds it crashes because of the error.

**Comment by brechtvdv** [comment]
I discovered the error comes from adding `named-graph: http://example.org/westtoer` to the repository materialiser config and happens when starting the pipeline a second time

**Comment by Yalz** [comment]
To be retested after Materialiser story is finished @jobulcke

**Comment by jobulcke** [comment]
This issue should be resolved in PR #536, but can be reopened if not.
The fix will be included in the next release, which will have the image tag `ldes/ldi-orchestrator:2.2.0-SNAPSHOT`.

A little remakr: since version 2.0.0, the config looks a litle different:

```yaml
orchestrator:
  pipelines:
    - name: touristattractions
      description: "This pipeline will take the latest version products from Westtoer, and send to an LDES server"
      input:
        name: Ldio:LdesClient
        config:
          url: https://ca-westtoer-ldes.bluesea-b3dcdb70.westeurope.azurecontainerapps.io/touristattractions
          sourceFormat: text/turtle
          retries:
            enabled: true
      transformers:
        - name: Ldio:VersionMaterialiser
          config:
            versionOf-property: http://purl.org/dc/terms/isVersionOf
      outputs:
        - name: Ldio:ConsoleOut
        - name: Ldio:RepositoryMaterialiser
          config:
            sparql-host: http://rdf4j-server:8080/rdf4j-server
            repository-id: jena
            named-graph: http://example.org/westtoer
```

Or the config can ever be further optimized, because since version 2.0.0, the materialiser can be enabled within the ldio ldes client config and the config would look like this
```yaml
orchestrator:
  pipelines:
    - name: touristattractions
      description: "This pipeline will take the latest version products from Westtoer, and send to an LDES server"
      input:
        name: Ldio:LdesClient
        config:
          url: https://ca-westtoer-ldes.bluesea-b3dcdb70.westeurope.azurecontainerapps.io/touristattractions
          sourceFormat: text/turtle
          materialisation:
            enabled: true
            verion-of-property: http://purl.org/dc/terms/isVersionOf
          retries:
            enabled: true
      outputs:
        - name: Ldio:ConsoleOut
        - name: Ldio:RepositoryMaterialiser
          config:
            sparql-host: http://rdf4j-server:8080/rdf4j-server
            repository-id: jena
            named-graph: http://example.org/westtoer
```
