### ISSUE TITLE
LDIO HttpInPoller: not passing url does not cause error

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-Linked-Data-Interactions#511]
**Describe the bug**
When not passing url as a property for Ldio:HttpInPoller, the poller doesn't crash or start.
This should not happen

**To Reproduce**
Passing this config, the pipeline will start with no result
```
orchestrator:
  pipelines:
    - name: demo
      input:
        name: Ldio:HttpInPoller
        config:
          interval: PT1S
          endpoint: https://brugge-ldes.geomobility.eu/observations/by-location
        adapter:
          name: Ldio:RdfAdapter
      outputs:
        - name: Ldio:ConsoleOut
```

**Expected behavior**
Application should give error
