### ISSUE TITLE
LDIO Ldes Client: not passing urls does not cause error

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-Linked-Data-Interactions#517]
**Describe the bug**
Due to parameter change from url to urls (and the new urls parameter allowing empty lists), no error is thrown.
This should be the case

**To Reproduce**
1. Create an Ldio config as follows:
```yaml
orchestrator:
  pipelines:
    - name: test-ldes
      input:
        name: Ldio:LdesClient
        config:
          url: https://private-api.gipod.vlaanderen.be/api/v1/ldes/mobility-hindrances?generatedAtTime=2021-01-06T18:04:12.173Z
          sourceFormat: application/ld+json
      outputs:
        - name: Ldio:ConsoleOut
          config:
            rdf-writer:
              content-type: application/n-quads
```
3. Immediately gets "No fragments to mutable or new fragments to process -> LDES ends."

Caused by name change from url to urls. 

**Expected behavior**
LDES Client follows given url
