### ISSUE TITLE
LdesClientConnector issues with dynamic pipelines

### ISSUE THREAD

**Issue by jobulcke** [Informatievlaanderen/VSDS-Linked-Data-Interactions#524]
**Describe the bug**
There are two bugs related to the LdesClientConnector, now that the dynamic pipelines are available
1. endpoints  `/admin/api/v1/pipeline/status` & `/admin/api/v1/pipeline/pipeline-name/status` are returning a `RUNNING` status instead of the expected INIT status when the connector is still waiting for a token
2. When you delete an LdesClientConnector pipeline, the MemoryTokenService is still looking/waiting for a token instead

**To Reproduce**
1. Provide and start an LDIO workbench with the following config:
```yaml
orchestrator:
  pipelines:
    - name: client-pipeline
      description: "Simple LdioLdesClientConnector in, console out pipeline."
      input:
        name: Ldio:LdesClientConnector
        config:
          urls: http://consumer-connector:29291/public
          connector-transfer-url: http://consumer-connector:29193/management/v2/transferprocesses
          proxy-url-to-replace: http://localhost:8081/devices
          proxy-url-replacement: http://consumer-connector:29291/public
          source-format: application/n-quads
        adapter:
          name: Ldio:RdfAdapter
      outputs:
        - name: Ldio:ConsoleOut
          config:
            rdf-writer:
              content-type: text/turtle
```
2. For the issue 1: poll the endpoints described at the top of this issue
3. For the issue 2: send a DELETE request to the `admin/api/v1/pipeline/client-pipeline` endpoint and check the logs where every 5 seconds a `waiting for token..` should appear

**Expected behavior**
For issue 1: `INIT` status instead of `RUNNING` status
For issue 2: No logging, and so no looking/waiting for a token, should be provided after deletion of the pipeline

**Suggestion**
For issue 2: In the LdioLdesClientConnector, shutdown should be overridden as well, where it shutdown the token service and it's threads
