### ISSUE TITLE
Unexpected behavior when no LdiAdapter is provided

### ISSUE THREAD

**Issue by jobulcke** [Informatievlaanderen/VSDS-Linked-Data-Interactions#525]
**Describe the bug**
No error/warning is logged when no adapter is provided at the pipeline creation since the dynamic pipelines, which results in a Internal server error when calling `/admin/api/v1/pipeline`, or even when the pipeline is created by the admin api

**To Reproduce**
1. Provide the following config and startup the orchestrator 
```yaml
orchestrator:
  pipelines:
    - name: client-pipeline
      description: "Simple LdioLdesClientConnector in, console out pipeline."
      input:
        name: Ldio:LdesClientConnector
        config:
          urls: http://consumer-connector:29291/public
          connector-transfer-url: http://consumer-connector:29193/management/v2/transferprocesses
          proxy-url-to-replace: http://localhost:8081/devices
          proxy-url-replacement: http://consumer-connector:29291/public
          source-format: application/n-quads
      outputs:
        - name: Ldio:ConsoleOut
          config:
            rdf-writer:
              content-type: text/turtle
```
2. make a GET request to `/admin/api/v1/pipieline`, an Internal Server Error will be returned

OR 
1. make a post request to `/admin/api/v1/pipeline` with the following content, which will result in an Internal Server Error
```yaml
---
name: client-pipeline
description: "Simple LdioLdesClientConnector in, console out pipeline."
input:
  name: Ldio:LdesClientConnector
  config:
    urls: http://consumer-connector:29291/public
    connector-transfer-url: http://consumer-connector:29193/management/v2/transferprocesses
    proxy-url-to-replace: http://localhost:8081/devices
    proxy-url-replacement: http://consumer-connector:29291/public
    source-format: application/n-quads
outputs:
  - name: Ldio:ConsoleOut
    config:
      rdf-writer:
        content-type: text/turtle
```

**Expected behavior**
1. In case an adapter is not required, a warning should be logged that no adapter is provided and no 500 status should be returned on fetching the pipeline overview
2. In case an adapter is required, an error should be logged and the creation should fail, eventually with a 400 status when the creation happens via the admin api
