### ISSUE TITLE
[Repository materialiser] Language tag of LangString added inside string

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/VSDS-Linked-Data-Interactions#545]
Version of LDIO: ldes/ldi-orchestrator:2.2.0-SNAPSHOT

Codelist I use: `https://github.com/sirus-be/westtoer-win-ldes2triplestore/blob/main/taxonomies/toeristische-regios.jsonld`

Pipeline:
```
    - name: taxonomies
      description: "This pipeline will fetch the product types and tree taxonomies."
      input:
        name: Ldio:HttpInPoller
        config:
          url:
            - https://sirus-be.github.io/westtoer-win-ldes2triplestore/taxonomies/toeristische-regios.jsonld
          cron: "*/60 * * * * *"
        adapter:
            name: Ldio:RdfAdapter
      outputs:
        - name: Ldio:ConsoleOut
        - name: Ldio:RepositoryMaterialiser
          config:
            sparql-host: http://rdf4j-server:8080/rdf4j-server
            repository-id: jena
            batch-size: 10
            batch-timeout: 10000
```

The output of the console looks good:
```
westtoer_ldes2triplestore_ldio-workbench  | concepts:3dfdd4ae-8a8b-4a77-9922-080fea077898
westtoer_ldes2triplestore_ldio-workbench  |         skos:prefLabel  "Vaatwasmachine"@de , "Vaatwasmachine"@fr , "Vaatwasmachine"@en , "Vaatwasmachine"@nl .
```

However, inside the triple store the language tag is added inside the string:
```
<https://westtoer.be/id/concept/producttype/cc11ef55-124f-4187-808a-8a63af55af42>
        <http://www.w3.org/2004/02/skos/core#prefLabel>
                "Dierenpark@de" , "Dierenpark@en" , "Dierenpark@fr" , "Dierenpark@nl" .
```

This occurs for all langstrings
