### ISSUE TITLE
HttpPoller logs no issues when a request fails and continueOnFail is not activated (default)

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-Linked-Data-Interactions#562]
**Describe the bug**
You get no information when the HttpPoller cannot reach an endpoint.

**To Reproduce**
Configure a default HttpPoller like

```
orchestrator:
  pipelines:
    - name: my-pipe
      input:
        adapter:
          name: Ldio:RdfAdapter
        name: Ldio:HttpInPoller
        config:
          url:
            - http://invalid-url.inventedexample
          interval: PT3S
      outputs:
        - name: Ldio:NoopOut
```

Notice how you see nothing in the logs, except that retries are done.

**Expected behavior**
A clear and concise log message of what went wrong.
