### ISSUE TITLE
When resume the pipeline halted by 404 error, the client doesn't as expected.

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-Linked-Data-Interactions#630]
**Versions**
[ldes/ldi-orchestrator:2.6.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/new?assignees=&labels=needs+triage&projects=&template=bug_report.md&title=#)

**Describe the bug**
Thanks to https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/605, when the client now faces 404 error, the pipeline is halted as expected.
But when the source `LDES` stream is recovered, manually resume the pipeline by API call, the pipeline doesn't continue consuming the `LDES` stream.

**To Reproduce**
1.  [ldes/ldi-orchestrator:2.6.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/new?assignees=&labels=needs+triage&projects=&template=bug_report.md&title=#) is up and running with the following configuration
```
server:
  port: 8080

orchestrator:
  pipelines:
    - name: bear-b-pipeline-client
      description: "bear-b dataset client for configured VSDS server"
      input:
        name: Ldio:LdesClient
        config:
          urls: http://ldes-server:8080/bearb/timebased-50
          source-format: "text/turtle"
      outputs:
            - name: Ldio:ConsoleOut
              config:
                content-type: text/turtle

spring:
  codec:
    max-in-memory-size: 10MB
    
logging:
  level:
    root: INFO
    Ldio.Application: INFO
    Ldio:HttpIn: DEBUG
    Ldio:HttpOut: DEBUG
```
`http://ldes-server:8080/bearb/timebased-50` is not available for moment => **UPDATED status for pipeline 'bear-b-pipeline-client' to HALTED** as expected
3.`http://ldes-server:8080/bearb/timebased-50` is back online
4. Call API `http://localhost:8082/admin/api/v1/pipeline/bear-b-pipeline-client/resume` to resume the pipeline

**Current behavior**
In the trace of LDIO we can see the pipeline is recovered, but it doesn't restart to consume the LDES stream.
![image](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/assets/15314807/ac1de5e6-0135-4487-a5b5-d6ade77c7212)

**Expected behavior**
The pipeline is recovered and continue consuming the stream `http://ldes-server:8080/bearb/timebased-50`. 
If resuming the pipeline doesn't' resume the function, there is no need to resume it..
