### ISSUE TITLE
org.apache.jena.datatypes prefix for non-string datatypes

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/VSDS-Linked-Data-Interactions#641]
LDIO version:  image: ldes/ldi-orchestrator:2.6.0-SNAPSHOT

Pipeline:
```
orchestrator:
  pipelines:
    - name: touristattractions
      description: "This pipeline will take members from IMJV, and send to an LDES server"
      input:
        name: Ldio:LdesClient
        config:
          urls:
            - https://ca-westtoer-ldes.bluesea-b3dcdb70.westeurope.azurecontainerapps.io/touristattractions
          sourceFormat: text/turtle
          materialisation:
            enabled: false
          retries:
            enabled: true
            max: 10
            statuses-to-retry: 403
      outputs:
        - name: Ldio:ConsoleOut
          config:
            rdf-writer:
              content-type: application/n-quads
        - name: Ldio:RepositoryMaterialiser
          config:
            sparql-host: http://rdf4j-server:8080/rdf4j-server
            repository-id: jena
```

Datatypes other than strings (double, custom URI) get a org.apache.jena.datatypes prefix inside the string:
```
<http://www.w3.org/ns/locn#geometry>
                [ a       <https://data.vlaanderen.be/ns/generiek#Geometrie>;
                  <http://www.w3.org/2003/01/geo/wgs84_pos#lat>
                          "org.apache.jena.datatypes.BaseDatatype$TypedValue@a72bbd98"^^<https://www.w3.org/2001/XMLSchema#double>;
                  <http://www.w3.org/2003/01/geo/wgs84_pos#long>
                          "org.apache.jena.datatypes.BaseDatatype$TypedValue@a6d1e164"^^<https://www.w3.org/2001/XMLSchema#double>
                ];
```

This was not the case with LDIO version:  image: ldes/ldi-orchestrator:1.13.0
