### ISSUE TITLE
Ldio:RepositorySink or Ldio:RepositoryMaterialiser > GraphDB

### ISSUE THREAD

**Issue by coret** [Informatievlaanderen/VSDS-Linked-Data-Interactions#667]
I'm trying to make a LDES client to synchronize LDES to GraphDB.

I started out with defining the output in the pipeline as `Ldio:RepositorySink` as documented on [VSDS Linked Data Interactions > LDIO Outputs > Repository Sink](https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/ldio/ldio-outputs/ldio-repository-sink) but when I posted the pipeline to the LDIO workbench the following error showed:
```
Pipeline "triple-store-pipeline": Invalid LDIO component in "Ldio:RepositorySink". Please validate by consulting the documentation.
```

Based on [VSDS Technical Documentation > Consuming Pipeline > Output components > Repository Materialization](https://informatievlaanderen.github.io/VSDS-Tech-Docs/consumer/outputs/repository-materialiser) (which has a non-working [reference guide](https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/ldio/ldio-outputs/ldio-repository-materialiser) link) I switched to `Ldio:RepositoryMaterialiser` as output. Now the pipeline is accepted by the LDIO workbench (using docker image: `ldes/ldi-orchestrator:2.5.1`).

But, then next error occurs, as the log shows a lot of the following:
```
ERROR - when='sendToMaterialiser', problem='org.eclipse.rdf4j.repository.RepositoryException: java.lang.IllegalStateException: Transaction URL has not been set'
```

I now start to wonder if the config for `Ldio:RepositorySink` at [VSDS Linked Data Interactions > LDIO Outputs > Repository Sink](https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/ldio/ldio-outputs/ldio-repository-sink) it correct/complete and is the same as the config for `Ldio:RepositoryMaterialiser`?

Below is my pipeline definition which generates the error above (the output config points to a GraphDB v10.6.1 instance on my local network which supports RDF4J v4.3.9):
```
name: triple-store-pipeline
description: "Requests all existing members from the LDES server and sends them to GraphDB"
input:
  name: Ldio:LdesClient
  config:
    urls: 
      - https://www.goudatijdmachine.nl/ldes/by-page
outputs:
  - name: Ldio:RepositoryMaterialiser 
    config:
      sparql-host: http://10.10.0.33:7200/
      repository-id: gtm
      named-graph: http://goudatijdmachine.nl/id/ldes-test
```
