### ISSUE TITLE
LDES Client fails to connect to Postgres database when using PostgreSQL persistence strategy in 2.13.0-SNAPSHOT

### ISSUE THREAD

**Issue by stijndns** [Informatievlaanderen/VSDS-Linked-Data-Interactions#758]
**Describe the bug**
When using the 2.13.0-SNAPSHOT version of the LDIO, an LDES client with a PostgreSQL persistence strategy fails to connect to the database in question, thereby causing the pipeline in its entirety to fail. Presumably, this is due to hibernate not selecting a driver.

**To Reproduce**
Using the following docker-compose and ldio pipeline YAML-files:

_docker-compose.yml_

```
services:
  ldio-workbench:
    container_name: postgres-example_ldio-workbench
    image: ldes/ldi-orchestrator:2.13.0-SNAPSHOT
    volumes:
      - ./ldio-postgres-example.yml:/ldio/application.yml:ro
    networks:
      - ldes
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: ldio
      POSTGRES_DB: ldiodb
      
    networks:
      - ldes

networks:
  ldes:
    driver: bridge
```

_ldio-postgres-example.yml_

```
orchestrator:
  pipelines:
    - name: touristattractions
      description: "This pipeline will take members from westtoerwin-nginx-prod, and send to Console"
      input:
        name: Ldio:LdesClient
        config:
          urls:
            - https://ca-westtoerwin-nginx-prod.livelyisland-1fa58ea1.westeurope.azurecontainerapps.io/touristattractions
          sourceFormat: text/turtle
          keep-state: true
          state: postgres
          postgres:
            url: jdbc:postgresql://postgres:5432/ldiodb
            username: ldio
            password: example
          materialisation:
            enabled: true
          retries:
            enabled: true
            max: 10
            statuses-to-retry: 403, 404
      outputs:
        - name: Ldio:ConsoleOut
```
When these containers are run, the resulting logs are:

[log_ldio_2_13_0.txt](https://github.com/user-attachments/files/19448827/log_ldio_2_13_0.txt)

On line 36 it can be seen that it attempts to use driver [null] for connecting with the postgres database.

**Expected behavior**
When changing the docker-compose file to use ldes/ldi-orchestrator:2.12.0-SNAPSHOT, the resulting logs are as follows:

[log_ldio_2_12_0.txt](https://github.com/user-attachments/files/19448830/log_ldio_2_12_0.txt)

On line 38 it can be seen that driver [org.postgresql.Driver] is used.
