### ISSUE TITLE
Sqlite connection doesn't work

### ISSUE THREAD

**Issue by razoreater** [Informatievlaanderen/VSDS-Linked-Data-Interactions#771]
The VLAG infrastructuur pipeline fails to initialize due to an incorrect SQLite path resolution, even though the volume is correctly mounted.

**Pipeline config snippet:**

- name: vlag-ldes-to-triplestore
```
- name: vlag-ldes-to-triplestore
  description: "This pipeline will take the latest version products from VLAG infrastructuur LDES, and send them to the triple store"
  input:
    name: Ldio:LdesClient
    config:
      state: sqlite
      sqlite.directory: /ldio/sqlite
      ...
```
**Kubernetes volume mount:**

```
volumes:
  - name: ldio-sqlite
    persistentVolumeClaim:
      claimName: ldio-sqlite

containers:
  - name: ldio-workbench-qa
    volumeMounts:
      - mountPath: /ldio/sqlite
        name: ldio-sqlite
```

**Observed error:**

java.sql.SQLException: path to './/ldio/ldio-sqlite//vlag-ldes-to-triplestore.db': '/ldio/./ldio' does not exist
Analysis:

This suggests either:

A bug in path resolution when combining sqlite.directory with a generated filename

Or an implicit default fallback appending ldio-sqlite when it cannot resolve sqlite.directory properly

Expected behavior:

With sqlite.directory: /ldio/sqlite, the SQLite file should be created under /ldio/sqlite/vlag-ldes-to-triplestore.db, which is a valid and mounted path.

Proposed fix:

Ensure that sqlite.directory is respected as an absolute path and no additional prefixes (like ldio/) are added during resolution.
